In [12]:

!pip install keras
#Remove '#' in above line if not installed keras 
import keras
import numpy as np
from sklearn.datasets import load_iris
dataset=load_iris()
##How data looks like?
print(dataset)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [13]:

##Step 1: Know the data
print(type(dataset))
print(len(dataset))

#Dataset is in bunch format. Bunch is a dictionary like object. 
print(dataset.keys())

#We try to find out what values are stored in these attributes 
print(dataset['data'][0:5]) 
print(dataset['target'][0:5]) 
print(dataset['target_names'][0:5])
print(dataset['DESCR'])
print(dataset['feature_names']) 
print(dataset['filename'])

#Next we define our x and y; y is the dependent on x
x=dataset ['data']

print(len(x)) #To check length of dataset
y=dataset['target']

#To check length of targets
print(len(y)) 

print(x[0])
print(y[0])

<class 'sklearn.utils.Bunch'>
8
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
['setosa' 'versicolor' 'virginica']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================


In [4]:
##Step 2 Convert y into one hot encoded vector

#One hot encoding is used because Y has labels (0,1,2)- which is a categorical 
#categorical data with no ordinal relationships 

from keras.utils import to_categorical

Ny=len(np.unique(y))
print(Ny)

Y=to_categorical(y,num_classes=Ny)
print(Y[0:5])

3
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [5]:
##Step 3: Now we split the data into two parts one for training another for testing 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,Y, test_size=0.10, shuffle=True)
print(x_train[0:5])
print(x_test[0:5])
print(y_train[0:5])
print(y_test[0:5])

[[6.1 3.  4.9 1.8]
 [5.9 3.2 4.8 1.8]
 [4.8 3.4 1.9 0.2]
 [6.4 2.8 5.6 2.2]
 [5.9 3.  4.2 1.5]]
[[5.  3.2 1.2 0.2]
 [6.7 2.5 5.8 1.8]
 [5.1 3.5 1.4 0.2]
 [5.6 2.9 3.6 1.3]
 [5.7 2.8 4.5 1.3]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [14]:
##Step 4: Then we normalize the data
from sklearn.preprocessing import StandardScaler

##Normalization is done so that the difference between highest and lowest data point is not too large
import numpy as np
scaler= StandardScaler()

##To find mean and std dev
scaler.fit(x_train)
##Converting data into form where mean of data is 0 and std dev is 1
X_train=scaler.transform(x_train)
X_test=scaler.transform(x_test)
print(np.amax(X_train,axis=0))
print(np.amin(X_train,axis=0))

[2.44623223 3.11562916 1.760489   1.67334753]
[-1.85347433 -2.02801654 -1.57259749 -1.44612658]


In [15]:
##Step : 5 : Now finally we build the model using keras
!pip install tensorflow
import keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(20, input_dim=X_train.shape[1], activation="relu"))
##Dropout is used to avoid overfitting
keras.layers.Dropout(0.2)
model.add(Dense (20, activation='relu'))
keras.layers.Dropout(0.2)
model.add(Dense (20, activation='relu'))
keras.layers.Dropout(0.2)
##For classification problems, we usually use softmax as activation function in final layer 
model.add(Dense(3, activation='softmax'))
##Compiling the model
model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['accuracy'])

In [16]:
# step 6: know the model
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 20)                100       
                                                                 
 dense_5 (Dense)             (None, 20)                420       
                                                                 
 dense_6 (Dense)             (None, 20)                420       
                                                                 
 dense_7 (Dense)             (None, 3)                 63        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [17]:

##Step 7 Train the model
##Batch size, epochs and validation split are all hyper parameters
model.fit(X_train, y_train, epochs=195, batch_size=80, validation_split=0.1)

Epoch 1/195
2/2 [==============================] - 1s 258ms/step - loss: 1.0548 - accuracy: 0.3306 - val_loss: 0.9326 - val_accuracy: 0.5000
Epoch 2/195
2/2 [==============================] - 0s 55ms/step - loss: 1.0248 - accuracy: 0.3306 - val_loss: 0.9095 - val_accuracy: 0.5714
Epoch 3/195
2/2 [==============================] - 0s 45ms/step - loss: 0.9961 - accuracy: 0.3471 - val_loss: 0.8860 - val_accuracy: 0.7857
Epoch 4/195
2/2 [==============================] - 0s 46ms/step - loss: 0.9667 - accuracy: 0.4793 - val_loss: 0.8637 - val_accuracy: 0.8571
Epoch 5/195
2/2 [==============================] - 0s 50ms/step - loss: 0.9397 - accuracy: 0.5868 - val_loss: 0.8397 - val_accuracy: 0.8571
Epoch 6/195
2/2 [==============================] - 0s 45ms/step - loss: 0.9117 - accuracy: 0.6529 - val_loss: 0.8156 - val_accuracy: 0.9286
Epoch 7/195
2/2 [==============================] - 0s 53ms/step - loss: 0.8852 - accuracy: 0.6612 - val_loss: 0.7911 - val_accuracy: 0.9286
Epoch 8/195
2/2 [==

2/2 [==============================] - 0s 53ms/step - loss: 0.1997 - accuracy: 0.9256 - val_loss: 0.3518 - val_accuracy: 0.8571
Epoch 60/195
2/2 [==============================] - 0s 45ms/step - loss: 0.1956 - accuracy: 0.9256 - val_loss: 0.3528 - val_accuracy: 0.8571
Epoch 61/195
2/2 [==============================] - 0s 32ms/step - loss: 0.1915 - accuracy: 0.9256 - val_loss: 0.3528 - val_accuracy: 0.8571
Epoch 62/195
2/2 [==============================] - 0s 50ms/step - loss: 0.1871 - accuracy: 0.9339 - val_loss: 0.3490 - val_accuracy: 0.8571
Epoch 63/195
2/2 [==============================] - 0s 38ms/step - loss: 0.1833 - accuracy: 0.9339 - val_loss: 0.3466 - val_accuracy: 0.8571
Epoch 64/195
2/2 [==============================] - 0s 34ms/step - loss: 0.1794 - accuracy: 0.9421 - val_loss: 0.3419 - val_accuracy: 0.8571
Epoch 65/195
2/2 [==============================] - 0s 34ms/step - loss: 0.1757 - accuracy: 0.9421 - val_loss: 0.3389 - val_accuracy: 0.8571
Epoch 66/195
2/2 [========

2/2 [==============================] - 0s 51ms/step - loss: 0.0646 - accuracy: 0.9835 - val_loss: 0.2873 - val_accuracy: 0.8571
Epoch 118/195
2/2 [==============================] - 0s 59ms/step - loss: 0.0638 - accuracy: 0.9835 - val_loss: 0.2859 - val_accuracy: 0.8571
Epoch 119/195
2/2 [==============================] - 0s 53ms/step - loss: 0.0628 - accuracy: 0.9835 - val_loss: 0.2844 - val_accuracy: 0.8571
Epoch 120/195
2/2 [==============================] - 0s 49ms/step - loss: 0.0620 - accuracy: 0.9835 - val_loss: 0.2808 - val_accuracy: 0.8571
Epoch 121/195
2/2 [==============================] - 0s 38ms/step - loss: 0.0613 - accuracy: 0.9835 - val_loss: 0.2812 - val_accuracy: 0.8571
Epoch 122/195
2/2 [==============================] - 0s 35ms/step - loss: 0.0604 - accuracy: 0.9835 - val_loss: 0.2883 - val_accuracy: 0.8571
Epoch 123/195
2/2 [==============================] - 0s 34ms/step - loss: 0.0598 - accuracy: 0.9835 - val_loss: 0.2950 - val_accuracy: 0.8571
Epoch 124/195
2/2 [=

Epoch 175/195
2/2 [==============================] - 0s 33ms/step - loss: 0.0392 - accuracy: 0.9917 - val_loss: 0.3408 - val_accuracy: 0.8571
Epoch 176/195
2/2 [==============================] - 0s 50ms/step - loss: 0.0390 - accuracy: 0.9917 - val_loss: 0.3528 - val_accuracy: 0.8571
Epoch 177/195
2/2 [==============================] - 0s 45ms/step - loss: 0.0389 - accuracy: 0.9917 - val_loss: 0.3578 - val_accuracy: 0.8571
Epoch 178/195
2/2 [==============================] - 0s 43ms/step - loss: 0.0388 - accuracy: 0.9917 - val_loss: 0.3628 - val_accuracy: 0.8571
Epoch 179/195
2/2 [==============================] - 0s 50ms/step - loss: 0.0387 - accuracy: 0.9917 - val_loss: 0.3620 - val_accuracy: 0.8571
Epoch 180/195
2/2 [==============================] - 0s 35ms/step - loss: 0.0384 - accuracy: 0.9917 - val_loss: 0.3520 - val_accuracy: 0.8571
Epoch 181/195
2/2 [==============================] - 0s 19ms/step - loss: 0.0380 - accuracy: 0.9917 - val_loss: 0.3388 - val_accuracy: 0.8571
Epoch 

In [18]:
##Step 8 Get the accuracy of model on testing data
testing=model.evaluate(X_test, y_test)

print("\n%s:%.2f%%" % (model.metrics_names[1]+'uracy of Model on testing data', testing[1]*100))

1/1 [==============================] - 0s 32ms/step - loss: 0.0062 - accuracy: 1.0000

accuracyuracy of Model on testing data:100.00%


In [19]:
##Step : 9: Evaluate our model
from sklearn.metrics import classification_report, confusion_matrix 
predictions = np.argmax(model.predict(X_test), axis=1) 
Y_test = np.argmax(y_test,axis=1)
#To get confusion matrix
print(confusion_matrix(Y_test, predictions))
#To get values of all evaluation metrics
print(classification_report (Y_test, predictions))

1/1 [==============================] - 0s 96ms/step
[[5 0 0]
 [0 7 0]
 [0 0 3]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

